# Generated by Django 6.0.6 on 2026-07-16 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWeb',
            fields=[
                ('idconfig', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración Web',
                'verbose_name_plural': 'Configuraciones Web',
                'db_table': 'ConfiguracionWeb',
            },
        ),
        migrations.CreateModel(
            name='UnidadMonetaria',
            fields=[
                ('idunidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('simbolo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Unidad Monetaria',
                'verbose_name_plural': 'Unidades Monetarias',
                'db_table': 'UnidadMonetaria',
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('idmensaje', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('idbingo', models.ForeignKey(db_column='idbingo', on_delete=django.db.models.deletion.CASCADE, to='bingo.bingo')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'db_table': 'MensajeChat',
            },
        ),
    ]
