# Generated by Django 6.0.6 on 2026-07-16 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_configuracionweb_unidadmonetaria_mensajechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='idunidadmonetaria',
            field=models.ForeignKey(blank=True, db_column='idunidadmonetaria', null=True, on_delete=django.db.models.deletion.PROTECT, to='bingo.unidadmonetaria', verbose_name='Unidad Monetaria'),
        ),
    ]
