# Generated by Django 4.2.16 on 2026-07-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_bingo_idunidadmonetaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidabingo',
            name='estadopremiomaterial',
            field=models.CharField(default='Ninguno', max_length=20, verbose_name='Estado del Premio Material'),
        ),
        migrations.AddField(
            model_name='partidabingo',
            name='horainiciopartida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Inicio de la Partida'),
        ),
        migrations.AddField(
            model_name='partidabingo',
            name='modalidad_victoria',
            field=models.CharField(default='Tabla Llena', max_length=50, verbose_name='Modalidad de Victoria'),
        ),
        migrations.AddField(
            model_name='partidabingo',
            name='sorteodesempate',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Sorteo de Desempate'),
        ),
        migrations.AlterField(
            model_name='partidabingo',
            name='bolascantadas',
            field=models.TextField(default='', verbose_name='Historial de Bolas Cantadas'),
        ),
        migrations.AlterField(
            model_name='partidabingo',
            name='estadopartida',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En Juego', 'En Juego'), ('Verificando', 'Verificando'), ('Desempate', 'Desempate'), ('Finalizada', 'Finalizada')], default='Programada', max_length=20, verbose_name='Estado de la Partida'),
        ),
        migrations.AlterField(
            model_name='partidabingo',
            name='ultimabola',
            field=models.IntegerField(default=0, verbose_name='Última Bola Cantada'),
        ),
    ]
