# Generated by Django 6.0.1 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_partidabingo_estadopremiomaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estadoprestamo',
            field=models.CharField(
                choices=[
                    ('Solicitado', 'Solicitado'),
                    ('Aprobado', 'Aprobado'),
                    ('En espera', 'En espera'),
                    ('Rechazado', 'Rechazado'),
                    ('Liquidado', 'Liquidado'),
                ],
                default='Solicitado',
                max_length=20,
                verbose_name='Estado del Préstamo',
            ),
        ),
    ]
